name: 'Upload dSYM to Firebase Crashlytics'
description: 'Upload dSYM file to Firebase Crashlytics'
inputs:
  key-regex:
    description: 'Regex to find issue key from commit'
    required: true
  build-number:
    description: 'Build number'
    required: true
  ios-release-url:
    description: 'Link to download iOS build'
    required: true
  ios-install-url:
    description: 'Link to install iOS build'
    required: true
  ios-version-name:
    description: 'Version name for iOS build'
    required: true
  android-release-url:
    description: 'Link to download Android build'
    required: true
  android-install-url:
    description: 'Link to install Android build'
    required: true
  android-version-name:
    description: 'Version name for Android build'
    required: true
  jira-host:
    description: 'Atlassian Jira host'
    required: true
outputs:
  message-payload:
    description: "Slack message payload"
    value: ${{ steps.build_payload.outputs.message_payload }}
runs:
  using: "composite"
  steps:
    - name: Build slack payload
      id: build_payload
      run: |
        ${{ github.action_path }}/slack_build_info_payload.sh ${{ github.action_path }}/slack-build-info-template.json
      shell: bash
      env:
        BUILD_NUMBER: ${{ inputs.build-number }}
        GIT_ACTOR: ${{ github.actor }}
        REF_NAME: ${{ github.ref }}
        JIRA_HOST: ${{ inputs.jira-host }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        ISSUE_KEY_REGEX: ${{ inputs.key-regex }}
        BUILD_URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
        IOS_VERSION_NAME: ${{ inputs.ios-version-name }}
        IOS_RELEASE_URL: ${{ inputs.ios-release-url }}
        IOS_INSTALL_URL: ${{ inputs.ios-install-url }}
        ANDROID_VERSION_NAME: ${{ inputs.android-version-name }}
        ANDROID_RELEASE_URL: ${{ inputs.android-release-url }}
        ANDROID_INSTALL_URL: ${{ inputs.android-install-url }}