name: 'Build slack message payload for Flutter'
description: 'Build slack message payload for Flutter'
inputs:
  key-regex:
    description: 'Regex to find issue key from commit'
    required: true
  build-number:
    description: 'Build number'
    required: true
  ios-release-url:
    description: 'Link to download iOS build'
    required: true
  ios-install-url:
    description: 'Link to install iOS build'
    required: true
  ios-version-name:
    description: 'Version name for iOS build'
    required: true
  android-release-url:
    description: 'Link to download Android build'
    required: true
  android-install-url:
    description: 'Link to install Android build'
    required: true
  android-version-name:
    description: 'Version name for Android build'
    required: true
  jira-host:
    description: 'Atlassian Jira host'
    required: true
outputs:
  message-payload:
    description: "Slack message payload"
runs:
  using: 'node12'
  main: 'dist/index.js'